@startuml

class Spot {
    id: UUID
    name: str
    description: str?
    longitude: float
    latitude: float
    created_at: DateTime
    updated_at: DateTime
    images: List[Image]
    --
    +create_spot(data: SpotCreate) : Spot
    +get_spot(spot_id: UUID) : Spot | None
    +get_by_coords(longitude: float, latitude: float) : Spot | None
    +get_all_spots() : Sequence[Spot]
    +get_spots_paginated(offset: int, limit: int) : Sequence[Spot]
    +update_spot(data: SpotUpdate) : Spot
    +delete_spot() : None
    +delete_all_spots() : None
}

class Image {
    id: UUID
    spot_id: UUID
    image_url: str
    uploaded_at: DateTime
    --
    +get_url() : str
}

Spot "1" -- "0..*" Image : images

@enduml